class VideoIdentifierException(ValueError): ...
class PlaylistIdentifierException(ValueError): ...
class ChannelIdentifierException(ValueError): ...

class ChannelUnavailableException(ValueError): ...
class PlaylistUnavailableException(ValueError): ...

class VideoUnavailableException(ValueError): ...
